package br.unitau.view;

import br.unitau.matriz.TabelaModelo;
import br.unitau.matriz.Cabecalho;
import br.unitau.matriz.MatrizDeInteiros;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.table.TableColumn;

/**
 *
 * @author Alinda
 */
public class TelaMatriz extends javax.swing.JFrame {

    private static final int CRIACAO = 0;
    private static final int INICIALIZACAO = 1;
    private static final int OPERACAO = 2;
    private MatrizDeInteiros matriz;
    private TabelaModelo tabelaModelo;
    private int estado;
    private int linha = 0;
    private int coluna = 0;

    public TelaMatriz() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFLinhaMatriz = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFColunaMatriz = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jSPTabelaDados = new javax.swing.JScrollPane();
        jTTabelaDados = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jBDefinirMatriz = new javax.swing.JButton();
        jBGerarMatriz = new javax.swing.JButton();
        jBDiagonaPrincipal = new javax.swing.JButton();
        jBSomaLinhas = new javax.swing.JButton();
        jBSomaColunas = new javax.swing.JButton();
        jBTransposta = new javax.swing.JButton();
        jBDiagSecundaria = new javax.swing.JButton();
        jBBuscaValor = new javax.swing.JButton();
        jBLimpar = new javax.swing.JButton();
        jBSomaMatriz = new javax.swing.JButton();
        jBMatrizSimetrica = new javax.swing.JButton();
        jBPAR = new javax.swing.JButton();
        jBMaiorValor = new javax.swing.JButton();
        jBRetornaIndice = new javax.swing.JButton();
        jBSubstitui = new javax.swing.JButton();
        jBInverter = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAResultado = new javax.swing.JTextArea();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Operações com Matriz de Inteiros");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordem da Matriz:"));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TelaMatriz.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TelaMatriz.this.focusLost(evt);
            }
        });

        jLabel1.setText("Linhas:");

        jTFLinhaMatriz.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TelaMatriz.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TelaMatriz.this.focusLost(evt);
            }
        });
        jTFLinhaMatriz.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validaCampo(evt);
            }
        });

        jLabel2.setText("Colunas:");

        jTFColunaMatriz.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validaCampo(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFLinhaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFColunaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFLinhaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTFColunaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Matriz:"));

        jTTabelaDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jSPTabelaDados.setViewportView(jTTabelaDados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSPTabelaDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSPTabelaDados, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Operações:"));

        jBDefinirMatriz.setText("Definir Matriz");
        jBDefinirMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDefinirMatrizActionPerformed(evt);
            }
        });

        jBGerarMatriz.setText("Gerar Matriz");
        jBGerarMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGerarMatrizActionPerformed(evt);
            }
        });

        jBDiagonaPrincipal.setText("Diag Principal");
        jBDiagonaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDiagonaPrincipalActionPerformed(evt);
            }
        });

        jBSomaLinhas.setText("Soma linhas");
        jBSomaLinhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSomaLinhasActionPerformed(evt);
            }
        });

        jBSomaColunas.setText("Soma colunas");
        jBSomaColunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSomaColunasActionPerformed(evt);
            }
        });

        jBTransposta.setText("Transposta");
        jBTransposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTranspostaActionPerformed(evt);
            }
        });

        jBDiagSecundaria.setText("Diag Secundaria");
        jBDiagSecundaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDiagSecundariaActionPerformed(evt);
            }
        });

        jBBuscaValor.setText("Busca Valor");
        jBBuscaValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscaValorActionPerformed(evt);
            }
        });

        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        jBSomaMatriz.setText("Somar Valores");
        jBSomaMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSomaMatrizActionPerformed(evt);
            }
        });

        jBMatrizSimetrica.setText("Matriz Simétrica");
        jBMatrizSimetrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMatrizSimetricaActionPerformed(evt);
            }
        });

        jBPAR.setText("Valores Pares");
        jBPAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPARActionPerformed(evt);
            }
        });

        jBMaiorValor.setText("Maior Valor");
        jBMaiorValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMaiorValorActionPerformed(evt);
            }
        });

        jBRetornaIndice.setText("Retorna índice");
        jBRetornaIndice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRetornaIndiceActionPerformed(evt);
            }
        });

        jBSubstitui.setText("Substituir Par e Ímpar");
        jBSubstitui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSubstituiActionPerformed(evt);
            }
        });

        jBInverter.setText("Inverter");
        jBInverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInverterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBBuscaValor, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addComponent(jBLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addComponent(jBDefinirMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBGerarMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBDiagonaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBSomaColunas, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addComponent(jBSomaLinhas, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addComponent(jBDiagSecundaria, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addComponent(jBTransposta, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addComponent(jBSomaMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBMatrizSimetrica, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addComponent(jBPAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBMaiorValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBRetornaIndice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jBSubstitui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBInverter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBBuscaValor, jBDefinirMatriz, jBDiagSecundaria, jBDiagonaPrincipal, jBGerarMatriz, jBLimpar, jBSomaColunas, jBSomaLinhas, jBTransposta});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBInverter, jBSubstitui});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jBDefinirMatriz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBGerarMatriz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBDiagonaPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBDiagSecundaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSomaLinhas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSomaColunas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTransposta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBBuscaValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBSomaMatriz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBMatrizSimetrica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBPAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBMaiorValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBRetornaIndice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSubstitui)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBInverter)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBDefinirMatriz, jBDiagSecundaria, jBDiagonaPrincipal, jBGerarMatriz, jBSomaColunas, jBSomaLinhas, jBTransposta});

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado:"));

        jTAResultado.setEditable(false);
        jTAResultado.setColumns(20);
        jTAResultado.setLineWrap(true);
        jTAResultado.setRows(5);
        jTAResultado.setTabSize(4);
        jTAResultado.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTAResultado);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int getEstado() {
        return estado;
    }

    private void jBDefinirMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDefinirMatrizActionPerformed
        if (jTFLinhaMatriz.getText().isEmpty() || (Integer.parseInt(jTFLinhaMatriz.getText()) <= 0 || Integer.parseInt(jTFLinhaMatriz.getText()) >= 10)) {
            JOptionPane.showMessageDialog(this, "Informe um valor válido para linhas", "Manipula Matriz", 0);
            jTFLinhaMatriz.setText("");
            jTFLinhaMatriz.requestFocusInWindow();
            return;

        }
        int lin = Integer.parseInt(jTFLinhaMatriz.getText());

        if (jTFColunaMatriz.getText().isEmpty() || (Integer.parseInt(jTFColunaMatriz.getText()) <= 0 || Integer.parseInt(jTFColunaMatriz.getText()) >= 10)) {
            JOptionPane.showMessageDialog(this, "Informe um valor válido para colunas", "Manipula Matriz", 0);
            jTFColunaMatriz.setText("");
            jTFColunaMatriz.requestFocusInWindow();
            return;

        }

        int col = Integer.parseInt(jTFColunaMatriz.getText());

        matriz = new MatrizDeInteiros(lin, col);
        linha = matriz.getTotLin();
        coluna = matriz.getTotCol();
        formataTabela();
        setEstado(1);
    }//GEN-LAST:event_jBDefinirMatrizActionPerformed

    private void jBGerarMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGerarMatrizActionPerformed
        matriz.setMatriz();
        formataTabela();
        setEstado(2);
    }//GEN-LAST:event_jBGerarMatrizActionPerformed

    private void formataTabela() {
        tabelaModelo = new TabelaModelo(matriz.getMatriz());
        jTTabelaDados.setModel(tabelaModelo);
        Cabecalho cabecalhoMatriz = new Cabecalho();
        TableColumn tc = jTTabelaDados.getColumn("");
        tc.setCellRenderer(cabecalhoMatriz);
        jTTabelaDados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);

    }

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        jTAResultado.setText("");
        jTFLinhaMatriz.setText(null);
        jTFColunaMatriz.setText(null);
        tabelaModelo.excluiLinhasTabela();
        jTFLinhaMatriz.requestFocusInWindow();
        linha = 0;
        coluna = 0;
        setEstado(0);
    }//GEN-LAST:event_jBLimparActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setEstado(0);
    }//GEN-LAST:event_formWindowOpened

    private void validaCampo(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validaCampo
        char tecla = evt.getKeyChar();
        if (!Character.isDigit(tecla)) {
            evt.consume();
        }
    }//GEN-LAST:event_validaCampo

    private void focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGained
        javax.swing.JTextField campo = (javax.swing.JTextField) evt.getSource();
        campo.setBackground(new Color(184, 207, 229));
        campo.requestFocusInWindow();
    }//GEN-LAST:event_focusGained

    private void focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusLost
        javax.swing.JTextField campo = (javax.swing.JTextField) evt.getSource();
        campo.setBackground(Color.white);
    }//GEN-LAST:event_focusLost

    private void jBDiagonaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDiagonaPrincipalActionPerformed
        jTAResultado.setText(matriz.vetorToString(matriz.diagonalPrincipal(), "Diagonal Principal\n"));
    }//GEN-LAST:event_jBDiagonaPrincipalActionPerformed

    private void jBDiagSecundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDiagSecundariaActionPerformed
        jTAResultado.setText(matriz.vetorToString(matriz.diagonalSecundaria(), "Diagonal Secundaria\n"));
    }//GEN-LAST:event_jBDiagSecundariaActionPerformed

    private void jBSomaMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSomaMatrizActionPerformed
        matriz.somaValores();
        jTAResultado.setText("Soma de todos os valores: " + matriz.somaValores());
    }//GEN-LAST:event_jBSomaMatrizActionPerformed

    private void jBSomaColunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSomaColunasActionPerformed
        matriz.somaColuna();
        jTAResultado.setText(matriz.vetorToString(matriz.somaColuna(), "Soma das colunas: "));
    }//GEN-LAST:event_jBSomaColunasActionPerformed

    private void jBSomaLinhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSomaLinhasActionPerformed
        matriz.somaLinha();
        jTAResultado.setText(matriz.vetorToString(matriz.somaLinha(), "Soma das linhas: "));
    }//GEN-LAST:event_jBSomaLinhasActionPerformed

    private void jBTranspostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTranspostaActionPerformed
        matriz.Transposta();
        jTAResultado.setText(matriz.matrizToString(matriz.Transposta(), "Matriz Transposta: "));

    }//GEN-LAST:event_jBTranspostaActionPerformed

    private void jBMatrizSimetricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMatrizSimetricaActionPerformed
        if (matriz.isSimetrica()) {
            jTAResultado.setText("Matriz simétrica");
        } else {
            jTAResultado.setText("Matriz NÃO É simétrica");
        }

    }//GEN-LAST:event_jBMatrizSimetricaActionPerformed

    private void jBPARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPARActionPerformed
        matriz.par();
        jTAResultado.setText(matriz.vetorToString(matriz.par(), "Matriz Transposta: "));
    }//GEN-LAST:event_jBPARActionPerformed

    private void jBMaiorValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMaiorValorActionPerformed
        matriz.maiorValor();
        jTAResultado.setText("O maior valor da matriz é: " + matriz.maiorValor());
    }//GEN-LAST:event_jBMaiorValorActionPerformed

    private void jBRetornaIndiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRetornaIndiceActionPerformed
        int numero = Integer.parseInt(JOptionPane.showInputDialog(null, "Qual número deseja procurar?"));

        if (matriz.retornaIndice(numero) > 0) {
            jTAResultado.setText(matriz.dados() + "\nO número procurado foi: " + numero + "\nO valor foi encontrado nas posições: " + matriz.retornaPosicao(numero));
        } else {
            jTAResultado.setText(matriz.dados() + "\nO valor não foi encontrado");
        }
    }//GEN-LAST:event_jBRetornaIndiceActionPerformed

    private void jBSubstituiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSubstituiActionPerformed
        matriz.substituiImpar();
        matriz.substituiPar();
        formataTabela();
        setEstado(2);
    }//GEN-LAST:event_jBSubstituiActionPerformed

    private void jBInverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInverterActionPerformed
        matriz.inverter();
        formataTabela();
        setEstado(2);
    }//GEN-LAST:event_jBInverterActionPerformed

    private void jBBuscaValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscaValorActionPerformed
        int numero = Integer.parseInt(JOptionPane.showInputDialog(this, "Informe o número que deseja buscar", "App", 0));
        matriz.busca(numero);
        
        jTAResultado.setText(matriz.valorExiste(numero));
    }//GEN-LAST:event_jBBuscaValorActionPerformed

    public void setEstado(int estado) {
        this.estado = estado;
        if (estado == CRIACAO) {
            jBDefinirMatriz.setEnabled(true);
            jBGerarMatriz.setEnabled(false);
            jBDiagonaPrincipal.setEnabled(false);
            jBDiagSecundaria.setEnabled(false);
            jBSomaLinhas.setEnabled(false);
            jBSomaColunas.setEnabled(false);
            jBTransposta.setEnabled(false);
            jBBuscaValor.setEnabled(false);
            jBLimpar.setEnabled(false);
        } else if (estado == INICIALIZACAO) {
            jBGerarMatriz.setEnabled(linha >= 1 && coluna >= 1);
            jBDefinirMatriz.setEnabled(false);
            jBDiagonaPrincipal.setEnabled(false);
            jBDiagSecundaria.setEnabled(false);
            jBSomaLinhas.setEnabled(false);
            jBSomaColunas.setEnabled(false);
            jBTransposta.setEnabled(false);
            jBBuscaValor.setEnabled(false);
            jBLimpar.setEnabled(false);
        } else if (estado == OPERACAO) {
            jBDefinirMatriz.setEnabled(false);
            jBGerarMatriz.setEnabled(linha >= 1 && coluna >= 1);
            jBDiagonaPrincipal.setEnabled(matriz.ehQuadrada());
            jBDiagSecundaria.setEnabled(matriz.ehQuadrada());
            jBSomaLinhas.setEnabled(linha >= 1 && coluna >= 2);
            jBSomaColunas.setEnabled(linha >= 2 && coluna >= 1);
            jBTransposta.setEnabled(linha >= 2 && coluna >= 2);
            jBBuscaValor.setEnabled(linha >= 1 && coluna >= 1);
            jBLimpar.setEnabled(linha >= 1 && coluna >= 1);
        }

    }

    /**
     * @param args the command line arguments"
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMatriz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscaValor;
    private javax.swing.JButton jBDefinirMatriz;
    private javax.swing.JButton jBDiagSecundaria;
    private javax.swing.JButton jBDiagonaPrincipal;
    private javax.swing.JButton jBGerarMatriz;
    private javax.swing.JButton jBInverter;
    private javax.swing.JButton jBLimpar;
    private javax.swing.JButton jBMaiorValor;
    private javax.swing.JButton jBMatrizSimetrica;
    private javax.swing.JButton jBPAR;
    private javax.swing.JButton jBRetornaIndice;
    private javax.swing.JButton jBSomaColunas;
    private javax.swing.JButton jBSomaLinhas;
    private javax.swing.JButton jBSomaMatriz;
    private javax.swing.JButton jBSubstitui;
    private javax.swing.JButton jBTransposta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jSPTabelaDados;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAResultado;
    private javax.swing.JTextField jTFColunaMatriz;
    private javax.swing.JTextField jTFLinhaMatriz;
    private javax.swing.JTable jTTabelaDados;
    // End of variables declaration//GEN-END:variables
}
